#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 10
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: wuxu92
disqus_show_comment_count: true

# site
title: wuxu
url: http://wuxu92.github.io
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: wuxu
author_email: wuxu92@gmail.com
author_info: <a href="http://wuxu92.github.io">wuxu92</a>
