#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: wuxu
disqus_show_comment_count: true

# site
title: wuxu's blog
url: http://wuxu.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: wuxu
author_email: wuxu92@gmail.com
author_info: <a href="http://wuxu92.github.com">wuxu92</a>
